language: c
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=default
      before_install: &bi
        - docker pull kazuho/h2o-ci:latest
        - chmod -R ugo+w .
      script:
        - make -f misc/docker-ci/check.mk
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=fuzz
      before_install: *bi
      script:
        - make -f misc/docker-ci/check.mk fuzz
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=openssl-1.1.0
      before_install: *bi
      script:
        - make -f misc/docker-ci/check.mk ossl1.1.0
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=openssl-1.1.1
      before_install: *bi
      script:
        - make -f misc/docker-ci/check.mk ossl1.1.1
    - os: linux
      sudo: required
      dist: bionic
      services:
        - docker
      env:
        - label=dtrace
      before_install: *bi
      script:
        - uname -a
        - make -f misc/docker-ci/check.mk dtrace CONTAINER_NAME=kazuho/h2o-ci:ubuntu1904
    - os: osx
      osx_image: xcode11.3
      env:
        - label=macOS
      cache: ccache
      addons:
        homebrew:
          update: true
          packages:
            - expect
            - nghttp2
            - ccache
      before_install:
        - curl -L https://cpanmin.us | perl - --nootest --self-upgrade --sudo
        - cpanm --sudo --installdeps --notest .
      script:
        - mkdir -p build
        - make -f misc/docker-ci/check.mk SRC_DIR="$PWD" _do-check
  fast_finish: true
  allow_failures:
      env: label=macOS
